/*Calculate total sales generated by each customer.*/

SELECT 
    cs.CustomerId,
	CONCAT(cs.FirstName,'',cs.LastName) AS Full_Name,
	sum(total) as Total_Value
FROM Customer as cs
JOIN Invoice as inv ON cs.CustomerId=inv.CustomerId
GROUP by cs.CustomerId,	cs.FirstName
ORDER by Total_Value DESC